# Generated by Django 3.2.13 on 2022-07-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_id',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
