# Generated by Django 3.2.13 on 2022-07-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_category_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image_1',
            field=models.ImageField(default='product image', upload_to='media/product_photos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image_2',
            field=models.ImageField(default='product image', null=True, upload_to='media/product_photos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image_3',
            field=models.ImageField(default='product image', null=True, upload_to='media/product_photos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image_4',
            field=models.ImageField(default='product image', null=True, upload_to='media/product_photos'),
        ),
    ]
