# Generated by Django 3.2.13 on 2022-07-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220715_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image_2',
            field=models.ImageField(blank=True, default='product image', null=True, upload_to='media/product_photos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image_3',
            field=models.ImageField(blank=True, default='product image', null=True, upload_to='media/product_photos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image_4',
            field=models.ImageField(blank=True, default='product image', null=True, upload_to='media/product_photos'),
        ),
    ]
