# Generated by Django 3.2.13 on 2022-07-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
