# Generated by Django 3.2.13 on 2022-07-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220716_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={},
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='user_permissions',
        ),
    ]
